export const PERSONAL_INFO = {
  name: "Ayush Bahuguna",
  email: "ayushbahuguna1122@gmail.com",
  phoneNumber: "",
  address: "India",
  resume:
    "https://drive.google.com/file/d/1hegdSp6lI4kw-sEzMG6tnjKGj3JYP0oq/view?usp=sharing",
  calDotCom: "https://cal.com/ayush-bahuguna-keo4nv",
  twitter: "@Ayush__Bahuguna",
  siteUrl: "https://ayush0portfolio.vercel.app",
  keywords: [
    "Ayush Bahuguna",
    "Full-Stack Developer",
    "React Native Developer",
    "Next.js Developer",
    "Software Engineer",
    "Web Development",
    "Mobile App Development",
    "Portfolio",
    "India",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "Expo",
    "Overshare App",
    "Splitzy App",
    "BLE Connect",
    "Feed4Me",
  ],
};
