import { TECH } from "./tech";

export const SKILLS = [
  TECH.NEXT_JS,
  TECH.REACT_NATIVE,
  TECH.REACT_JS,
  TECH.TYPESCRIPT,
  TECH.AWS,
  TECH.NODE_JS,
  TECH.EXPRESS_JS,
  TECH.TAILWIND,
  TECH.BOOTSTRAP,
  TECH.MATERIAL_UI,
  TECH.MONGO_DB,
  TECH.HTML,
  TECH.SOCKET_IO,
  TECH.CSS,
  TECH.JAVASCRIPT,
  TECH.JAVA,
  TECH.GITHUB,
  TECH.GIT,
  TECH.FIREBASE,
  TECH.REST_API,
  TECH.EXPO,
  TECH.GSAP,
];

export const SOFTWARE = [
  TECH.PHOTOSHOP,
  TECH.CANVA,
  TECH.NETLIFY,
  TECH.GITHUB,
  TECH.GIT,
  TECH.VS_CODE,
  TECH.POSTMAN,
  TECH.RENDER,
];
